import pygame

ANCHO_PANTALLA = 1400
ALTO_PANTALLA = 700
SIZE_SCREEN = (ANCHO_PANTALLA, ALTO_PANTALLA)
PANTALLA = pygame.display.set_mode(SIZE_SCREEN)
FPS = 60
RELOJ = pygame.time.Clock()

# RECURSOS
PATH_IMG = 'GAME\Recursos\img\\'
PATH_FONDO = 'GAME\Recursos\img\\fondo\\'
PATH_PLATAFORMAS = 'GAME\Recursos\img\\plataformas\\'

# PLAYER
ANCHO_PERSONAJE = 120
ALTO_PERSONAJE = 120
TAMAÑO_PERSONAJE = (ANCHO_PERSONAJE, ALTO_PERSONAJE)
VELOCIDAD_X = 15
VELOCIDAD_Y = 15
TOPE_Y = (195,450)

# ENEMYS
ANCHO_ENEMIGO = 150
ALTO_ENEMIGO = 180
TAMAÑO_ENEMIGO = (ANCHO_ENEMIGO, ALTO_ENEMIGO)

# PLATAFORMAS


