import pygame

ANCHO_PANTALLA = 1200
ALTO_PANTALLA = 600
SIZE_SCREEN = (ANCHO_PANTALLA, ALTO_PANTALLA)
PANTALLA = pygame.display.set_mode(SIZE_SCREEN)
FPS = 12
RELOJ = pygame.time.Clock()

# RECURSOS
PATH_IMG = 'GAME\Recursos\img\\'
PATH_FONDO = 'GAME\Recursos\img\\fondo\\'

# PLAYER
ANCHO_PERSONAJE = 150
ALTO_PERSONAJE = 150
TAMAÑO_PERSONAJE = (ANCHO_PERSONAJE, ALTO_PERSONAJE)
VELOCIDAD_X = 15
VELOCIDAD_Y = 15
TOPE_Y = (195,450)

# ENEMYS

